### ISSUE TITLE
The Apk crash

### ISSUE THREAD

**Issue by xixiangnanhai** [nekocode/CameraFilter#5]
the apk that you provide  run  on my device crash

**Comment by nekocode** [comment]
Can you provide more information? Such as system version, device name or crash log.

**Comment by ArtemSel** [comment]
When i try to launch app (first start) - app crashed (Xiaomi MI Note and Nexus 5). When i reopen the app - works stable. I think, problem with runtime permissions

E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: cn.nekocode.camerafilter, PID: 17356
                  java.lang.NullPointerException: Attempt to invoke virtual method 'void cn.nekocode.camerafilter.filter.CameraFilter.onAttach()' on a null object reference
                      at cn.nekocode.camerafilter.CameraRenderer.setSelectedFilter(CameraRenderer.java:128)
                      at cn.nekocode.camerafilter.MainActivity$1.onTouch(MainActivity.java:94)
                      at android.view.View.dispatchTouchEvent(View.java)
                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java)
                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java)
                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java)
                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java)
                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java)
                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java)
                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java)
                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java)
                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java)
                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java)
                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java)
                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java)
                      at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java)
                      at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java)
                      at android.app.Activity.dispatchTouchEvent(Activity.java)
                      at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:63)
                      at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java)
                      at android.view.View.dispatchPointerEvent(View.java)
                      at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java)
                      at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java)
                      at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java)
                      at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java)
                      at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java)
                      at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java)
                      at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java)
                      at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java)
                      at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java)
                      at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java)
                      at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java)
                      at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java)
                      at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java)
                      at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java)
                      at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java)
                      at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java)
                      at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java)
                      at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java)
                      at android.os.MessageQueue.nativePollOnce(Native Method)
                      at android.os.MessageQueue.next(MessageQueue.java)
                      at android.os.Looper.loop(Looper.java)
                      at android.app.ActivityThread.main(ActivityThread.java)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)

**Comment by nekocode** [comment]
@ArtemSel  I have just fixed this issue on the [version 2.2](https://github.com/nekocode/CameraFilter/releases/tag/2.2).
