### ISSUE TITLE
Error while changing view visibility

### ISSUE THREAD

**Issue by qssq** [nekocode/CameraFilter#8]
va.lang.IllegalThreadStateException: Thread already started
                                                                         at java.lang.Thread.checkNotStarted(Thread.java:849)
                                                                         at java.lang.Thread.start(Thread.java:1059)
                                                                         at cn.nekocode.camerafilter.CameraRenderer.onSurfaceTextureAvailable(CameraRenderer.java:121)

**Comment by nekocode** [comment]
Thanks for your feedback. I will fix it later.

**Comment by nekocode** [comment]
I try to fix it in [this commit](https://github.com/nekocode/CameraFilter/commit/ec2b7c42b97ce7f079a38463a3af20b72c35f3da). 
Please have a try. If it doesn't work for you, please reopen this issue and give me more information about your problem.

**Comment by qssq** [comment]
好吧，谢谢了有空试下，当时项目紧迫，我就又还原成以前的margic camera了。 对了不知道您的可以修改是否为前置或者后置摄像头。
